# Generated by Django 5.1.1 on 2025-02-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('funfact', models.TextField()),
                ('type', models.CharField(choices=[('coastal', 'Coastal'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='FamousFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('city', models.ManyToManyField(related_name='famous_food', to='cities.city')),
            ],
        ),
    ]
