# Generated by Django 5.1.1 on 2025-02-05 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='famousfood',
            options={'ordering': ['name']},
        ),
    ]
