# Generated by Django 5.1.1 on 2025-02-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0002_alter_famousfood_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['name']},
        ),
    ]
