# Generated by Django 5.1.1 on 2025-02-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_alter_city_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='CateringPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=200)),
                ('district', models.TextField(null=True)),
                ('suburb', models.TextField(null=True)),
                ('street', models.TextField(null=True)),
                ('formatted', models.TextField(null=True)),
                ('categories', models.JSONField()),
                ('amenity', models.CharField(max_length=100, null=True)),
                ('house_number', models.IntegerField(null=True)),
                ('website', models.URLField(max_length=100, null=True)),
                ('opening_hours', models.CharField(max_length=200, null=True)),
                ('contact', models.JSONField(null=True)),
                ('facilities', models.JSONField(null=True)),
                ('catering', models.JSONField(null=True)),
            ],
        ),
    ]
