# Generated by Django 5.1.1 on 2025-02-05 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_cateringplace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringplace',
            name='house_number',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
