# Generated by Django 5.1.1 on 2025-02-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_alter_cateringplace_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='cateringplace',
            name='email',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='cateringplace',
            name='phone',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='cateringplace',
            name='categories',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='cateringplace',
            name='catering',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cateringplace',
            name='contact',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='cateringplace',
            name='facilities',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
