# Generated by Django 5.1.1 on 2025-02-06 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_alter_cateringplace_amenity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cateringplace',
            name='amenity',
        ),
    ]
