# Generated by Django 5.1.1 on 2025-02-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_remove_cateringplace_amenity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringplace',
            name='email',
            field=models.EmailField(blank=True, max_length=200, null=True),
        ),
    ]
