# Generated by Django 5.1.1 on 2025-02-06 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_alter_cateringplace_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringplace',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city'),
        ),
    ]
