# Generated by Django 5.1.1 on 2025-02-06 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_cateringplace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cateringplace',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='city_place', to='cities.city'),
        ),
    ]
