# Generated by Django 5.1.1 on 2025-02-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0014_shoppingmallsplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoppingmallsplace',
            name='catering',
        ),
    ]
