# Generated by Django 5.1.1 on 2025-02-08 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_remove_shoppingmallsplace_catering'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingmallsplace',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='cities.city'),
        ),
    ]
