# Generated by Django 5.1.1 on 2025-02-08 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0016_alter_shoppingmallsplace_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoppingmallsplace',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopping_place', to='cities.city'),
        ),
        migrations.CreateModel(
            name='Accommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('country_code', models.CharField(max_length=10)),
                ('district', models.TextField(blank=True, null=True)),
                ('suburb', models.TextField(blank=True, null=True)),
                ('street', models.TextField(blank=True, null=True)),
                ('formatted', models.TextField(blank=True, null=True)),
                ('categories', models.CharField(max_length=100)),
                ('house_number', models.CharField(blank=True, max_length=1000, null=True)),
                ('website', models.URLField(blank=True, max_length=100, null=True)),
                ('opening_hours', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=100, null=True)),
                ('facilities', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation', to='cities.city')),
            ],
        ),
    ]
