# Generated by Django 5.1.1 on 2025-02-10 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0017_alter_shoppingmallsplace_city_accommodation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='type',
            field=models.CharField(choices=[('coastal', 'Coastal'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('dessert', 'Dessert')], max_length=100),
        ),
    ]
