# Generated by Django 5.1.1 on 2025-02-14 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0018_alter_city_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='type',
            field=models.CharField(choices=[('coastal', 'Coastal'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('desert', 'Desert')], max_length=100),
        ),
    ]
