# Generated by Django 5.1.1 on 2025-02-14 19:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0019_alter_city_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='image',
            field=cloudinary.models.CloudinaryField(default='http://res.cloudinary.com/djibubqdg/image/upload/v1739547762/g2kxssiifzsqbac9tar3.jpg', max_length=255, verbose_name='image'),
        ),
    ]
