# Generated by Django 5.1.5 on 2025-02-20 14:43

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0021_cateringplace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='accommodation',
            name='image',
            field=cloudinary.models.CloudinaryField(default='catering_places/caf.jpg', max_length=255, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='shoppingmallsplace',
            name='image',
            field=cloudinary.models.CloudinaryField(default='catering_places/caf.jpg', max_length=255, verbose_name='image'),
        ),
    ]
