# Generated by Django 5.1.5 on 2025-02-20 15:19

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0022_accommodation_image_shoppingmallsplace_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='entertainmentplace',
            name='image',
            field=cloudinary.models.CloudinaryField(default='catering_places/caf.jpg', max_length=255, verbose_name='image'),
        ),
    ]
