# Generated by Django 5.1.5 on 2025-02-21 10:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0023_entertainmentplace_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accommodation_place', to='cities.city'),
        ),
        migrations.AlterField(
            model_name='cateringplace',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catering_place', to='cities.city'),
        ),
    ]
