# Generated by Django 5.1.1 on 2025-02-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('Female', 'Female'), ('Male', 'Male')], default='seba', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=models.ImageField(default='media/places_images/Colored_Canyon.jpg', upload_to='user_images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='phone_no',
            field=models.CharField(default='01014452898', max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
