# Generated by Django 5.1.1 on 2025-02-14 03:07

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_customuser_country_customuser_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(default='user_images/', max_length=255, verbose_name='image'),
        ),
    ]
