# Generated by Django 5.1.1 on 2025-02-10 20:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cities', '0017_alter_shoppingmallsplace_city_accommodation'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Historical', 'Historical'), ('Natural_Attrctions', 'Natural_Attrctions'), ('Beach', 'Beach'), ('Religious_Attraction', 'Religious_Attraction'), ('Modern_Attracation', 'Modern_Attracation'), ('Desert_Attraction', 'Desert_Attraction')], max_length=100)),
                ('image', models.ImageField(upload_to='places_images/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.city')),
            ],
        ),
    ]
