# Generated by Django 5.1.1 on 2025-02-10 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packageplace',
            name='description',
            field=models.TextField(default='desc'),
            preserve_default=False,
        ),
    ]
