# Generated by Django 5.1.1 on 2025-02-14 03:12

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0002_packageplace_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packageplace',
            name='image',
            field=cloudinary.models.CloudinaryField(default='places_images/', max_length=255, verbose_name='image'),
        ),
    ]
