# Generated by Django 5.1.5 on 2025-02-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favorites', '0002_remove_favorite_places_favorite_places'),
        ('packages', '0003_alter_packageplace_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='places',
        ),
        migrations.AddField(
            model_name='favorite',
            name='places',
            field=models.ManyToManyField(to='packages.packageplace'),
        ),
    ]
