# Generated by Django 5.1.1 on 2025-02-15 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_like_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='author',
        ),
    ]
