# Generated by Django 5.1.5 on 2025-02-18 19:44

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_like_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(default='default_blog_photo.jpg', max_length=255, verbose_name='image'),
        ),
    ]
