# Generated by Django 5.1.5 on 2025-02-18 19:55

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/djibubqdg/image/upload/v1739908442/pvs4pbsiimdivm3qlzb8.jpg', max_length=255, verbose_name='image'),
        ),
    ]
