# Generated by Django 5.1.5 on 2025-02-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='city',
            field=models.CharField(max_length=150),
        ),
    ]
