# Generated by Django 5.1.1 on 2025-02-10 23:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Historical', 'Historical'), ('Natural_Attrctions', 'Natural_Attrctions'), ('Beach', 'Beach'), ('Religious_Attraction', 'Religious_Attraction'), ('Modern_Attracation', 'Modern_Attracation'), ('Desert_Attraction', 'Desert_Attraction')], max_length=50)),
                ('user', models.ManyToManyField(related_name='user_experiences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
